// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcsrhljwmjjrezowihqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjc3JobGp3bWpqcmV6b3dpaHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDY1ODYsImV4cCI6MjA2NzIyMjU4Nn0.V0_eiEmxLlZ1A5yUvRj3OQf5EfTXSUxq31eE6tdWKfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});